# fly.toml app configuration file generated for predicine-backend2 on 2025-04-12T02:32:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'predicine-backend2'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  PORT=3000
  REFRESH_TOKEN_LIFETIME = "1y"
  ACCESS_TOKEN_LIFETIME = "1y"
  ACCESS_TOKEN_LIFETIME_AFTER_LOGIN = "15y"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
